Gym-config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
"""URLs for accounts app."""
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Athlete login page
    # path('login/', views.login_view, name='athlete-login'),
    # Log out page
    path('logout/', views.logout_view, name='logout'),
    # Athlete registration page.
    path('register/', views.register_account_view, name='register'),
    # Successful registration
    path('register/successful-registration/',
         views.successful_registration, name='successful_registration'),
    # Athlete profile
    path('profile/', views.profile_view, name='profile'),
    # Physical information page.
    path('profile/physical-information/', views.physical_information_view, name='physical-information'),
    # Trainer registration page.
    path('trainer_register/', views.register_trainer_account_view, name='trainer_registeration'),
    # Trainer login page.
    path('trainer_login/', views.trainer_login_view, name='trainer-login'),
    # Trainer profile page.
    path('trainer_profile/', views.trainer_profile_view, name='trainer_profile'),
    # Athlete login page
    path('login/account/', views.login_view, name='athlete-login'),
    # Trainer login page
    path('login/trainer_account/', views.trainer_login_view, name='trainer-login'),
    # Exercise program page
    path('profile/program/', views.program_view, name='exc-program'),
]

gym/urls.py
"""""URLs for gym app."""""
from django.urls import path
from . import views

app_name = 'gym'

urlpatterns = [
    path('', views.home, name='home'),
    path('trainers/', views.trainers, name='trainers'),
    path('gyms/', views.gyms_view, name='gyms'),
    path('exc-list/',views.exc_list, name='exc-list'),
]

gym/models.py
from django.db import models

# Create your models here.

gym/views.py
from django.shortcuts import render
from accounts.models import TrainerAccount

def home(request):
    """Home Page"""
    return render(request, 'gym/home.html')

def trainers(request):
    """Shows list of all trainers."""
    trainers = TrainerAccount.objects.order_by('date_joined')
    return render(request, 'gym/trainers.html', {'trainers' : trainers})

def gyms_view(request):
    """Shows list of all gyms."""
    return render(request, 'gym/gyms.html')

def exc_list(request):
    """Shows list of all exercises."""
    return render(request, 'gym/exercises-list.html')

gym/templates/gym/article1.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ورزش‌یار</title>
  <link rel="icon" href="strength.png">
  <link rel="stylesheet" href="article1.css">
</head>

<header class="sticky">
  <div id="logo">
    <h2>ورزش‌یار</h2>
  </div>
  <div class="header_links">
    <div>
      <a class="header_nav" href="../home.html">صفحه اصلی</a>
      <a class="header_nav" href="">باشگاه ها</a>
      <a class="header_nav" href="">مربی ها</a>
    </div>
    <div>
      <a class="header_nav profile" href="">پروفایل</a>
    </div>
  </div>
</header>

<body>
  <main class="content">
    <article>
      <h2>نقش بهداشت در سلامتی</h2>
      <img src="gym.jpg">
      <p>
        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون
        بلکه
        روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز،
        و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد،<br /> کتابهای زیادی در شصت و سه درصد گذشته حال و آینده،
        شناخت فراوان جامعه و متخصصان
        را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در
        زبان فارسی ایجاد کرد،
        در این صورت می توان امید داشت که تمام و دشواری <br />
        موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی
        سوالات پیوسته اهل دنیای
        موجود طراحی اساسا مورد استفاده قرار گیرد.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده
        از طراحان گرافیک است،
        چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و
        کاربردهای متنوع با هدف بهبود
        ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می
        طلبد، تا با نرم افزارها
        شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی،
      </p>
      <img src="work-out.png">
      <p> و فرهنگ پیشرو در زبان فارسی ایجاد کرد،<br /> در این صورت می توان امید داشت که
        تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای
        اصلی، و جوابگوی
        سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
        از صنعت چاپ، و با
        استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط
        فعلی تکنولوژی مورد
        نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد،<br /> کتابهای زیادی در شصت و سه درصد گذشته حال و
        آینده، شناخت فراوان
        جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و
        فرهنگ پیشرو در
        زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ
        به پایان رسد و
        زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده
        قرار گیرد.
      </p>
    </article>
  </main>
</body>
<footer>
  <h4>ارتباط با ما</h4>
  <h4>پشتیبانی</h4>
  <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
</footer>

</html>

gym/templates/gym/exercises-list.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>حرکات ورزشی</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'gym/exercises-list.css' %}">
    <link rel="icon" href="{% static 'gym/svg/strength.png' %}">
    <script src="{% static 'gym/gyms.js' %}"></script>
</head>

<header class="sticky">
    <span class="header">
        <div id="logo">
            <h2>ورزش‌یار</h2>
        </div>
        <div class="header_links">
            <div>
                <a class="header_nav" href="{% url 'gym:home' %}">صفحه اصلی</a>
                <a class="header_nav" href="{% url 'gym:gyms' %}">باشگاه ها</a>
                <a class="header_nav" href="{% url 'gym:trainers' %}">مربی ها</a>
                <a class="header_nav" href="{% url 'gym:exc-list' %}">حرکات ورزشی</a>
            </div>
            <div>
                {% if user.is_authenticated %} {{ user.username }} عزیز، خوش آمدید!
                <a class="header_nav profile" href="{% url 'accounts:profile' %}">پروفایل</a>
                {% else %}
                <a class="header_nav profile" href="{% url 'accounts:trainer-login' %}">پنل مربیان</a>
                <a class="header_nav profile" href="{% url 'accounts:athlete-login' %}">پنل ورزشکاران</a>
                {% endif %}
            </div>
        </div>
    </span>
    <div class="mobile-header">
        <div class="dropdown">
            <button onclick="myFunction()" class="dropbtn">ورزش‌یار</button>
            <div id="myDropdown" class="dropdown-content">
                <a href="{% url 'gym:home' %}">صفحه اصلی</a>
                <a href="{% url 'gym:gyms' %}">باشگاه ها</a>
                <a href="{% url 'gym:trainers' %}">مربی ها</a>
                <a href="{% url 'gym:exc-list' %}">حرکات ورزشی</a>
                {% if user.is_authenticated %}<!-- {{ user.username }} عزیز، خوش آمدید! -->
                <a href="{% url 'accounts:profile' %}">پروفایل</a>
                {% else %}
                <a href="{% url 'accounts:trainer-login' %}">پنل مربیان</a>
                <a href="{% url 'accounts:athlete-login' %}">پنل ورزشکاران</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<body>
    <main>
        <h2>نحوه انجام انواع حرکات ورزشی</h2>
        <span class="exercises-list">
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Squat-with-Dumbbells.gif' %}" alt="">
                <h3>اسکوات جفت دمبل</h3>
                <h5>گروه‌های عضلانی هدف:<br>لگن و پا</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Lever-Deadlift.gif' %}" alt="">
                <h3>داخل ران سیمکش</h3>
                <h5>گروه‌های عضلانی هدف:<br>عضلات داخلی ران و پا</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\outer-thigh.gif'%}">
                <h3>پشت ران سیمکش</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>پشت پا (همسترینگ)</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\dumbbell-single-leg-hip-thrust.gif'%}">
                <h3>هپ تراست نشسته</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>عضلات گلوتئال و پشت پا</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\dumbbell-kickbacks-for-triceps.gif'%}">
                <h3>کیک بک دمبل آزاد</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>پشت بازو</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Fly_Chest.gif'%}">
                <h3>فلای دستگاه</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>عضله سینه و سه‌سر بازو</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\outer-thigh-cable.gif'%}">
                <h3>خارج ران سیمکش</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>خارج ران</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\standing-calf-raise.gif'%}">
                <h3>ساق پا ایستاده</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>دو قلو ساق پا</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\squat.gif'%}">
                <h3>سلام ژاپنی</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>شکم، فیله و پا</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Press_Chest.gif'%}">
                <h3>بالا سینه هالتر دو ضرب</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>عضلات بالایی سینه و ساعد</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\single-arm.gif'%}">
                <h3>قفسه سینه تک دست</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>قفسه سینه</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\tricep-pushdown.gif'%}">
                <h3>پشت بازو سیمکش</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>پشت بازو</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Military-Press.gif'%}">
                <h3>سینه نظامی روی بالا سینه</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>سینه و بازو</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\cable-crunch.gif'%}">
                <h3>کرانچ اوت</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>عضله راست شکمی و دنده‌ای </h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Single-Shoulder-Press.gif'%}">
                <h3>سرشانه دمبل تک دست</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>سرشانه جلویی</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\French-Press.gif'%}">
                <h3>پشت بازو فرانسوی</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>سه سربازویی (پشت بازو)</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Face-Pull.gif'%}">
                <h3>پول فیس</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>بخش پشتی سرشانه</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Seated-Cable-Rope.gif'%}">
                <h3>قایقی دست باز</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>پشتی بزرگ و گرد بزرگ</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Lateral-raise_Shoulders.gif'%}">
                <h3>نشرخم دو جانبه</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>بخش پشت سرشانه</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\plank.gif'%}">
                <h3>پلنک</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>شکم، شانه، دست و پاها</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\Machine-Flys.gif'%}">
                <h3>فلی بک</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>سرشانه پشتی</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\russian-twist.gif'%}">
                <h3>چرخش روسی</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>عضلات شکم و بخش پایینی کمر</h5>
            </div>
            <div class="exercise">
                <img src="{% static 'gym\svg\exercises-list\moun.gif'%}">
                <h3>کوه‌نوردی</h3>
                <h5>گروه‌های عضلانی هدف:</h5>
                <h5>شانه، دستها، کمر و پاها</h5>
            </div>
        </span>
    </main>
</body>
<footer>
    <h4>ارتباط با ما</h4>
    <h4>پشتیبانی</h4>
    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
</footer>

</html>

gym/templates/gym/home.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ورزش‌یار</title>
  {% load static %}
  <link rel="icon" href="../static/gym/svg/strength.png" />
  <link rel="stylesheet" href="../../static/gym/home.css" />
  <script src="{% static 'gym/gyms.js' %}"></script>
</head>


<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ورزش‌یار</title>
  {% load static %}
  <link rel="icon" href="../static/gym/svg/strength.png">
  <link rel="stylesheet" href="../../static/gym/home.css">
  <script src="{% static 'gym/gyms.js' %}"></script>
</head>

<header class="sticky">
  <span class="header">

    <div class="header_links">
      <div>
        <a class="header_nav" id="nv" href="{% url 'gym:home' %}">صفحه اصلی</a>
        <a class="header_nav" id="nv" href="{% url 'gym:gyms' %}">باشگاه ها</a>
        <a class="header_nav" id="nv" href="{% url 'gym:trainers' %}">مربی ها</a>
        <a class="header_nav" id="nv" href="{% url 'gym:exc-list' %}">حرکات ورزشی</a>

      </div>
      <div>
        <span id="welcome">
          {% if user.is_authenticated %}
          {% if user_type == 'account' %}
          {{ user.username }} عزیز، خوش آمدید!
          <a class="header_nav profile" href="{% url 'accounts:profile' %}">پروفایل‌ من</a>
          <a class="header_nav profile" href="{% url 'accounts:logout' %}">خروج</a>
          {% elif user_type == 'trainer' %}
          {{ user.username }} عزیز، خوش آمدید!
          <a class="header_nav profile" href="{% url 'accounts:trainer_profile' %}">پروفایل‌ من</a>
          <a class="header_nav profile" href="{% url 'accounts:logout' %}">خروج</a>
          {% endif %}
          {% else %}
          <a class="header_nav profile" href="{% url 'accounts:trainer-login' %}">پنل مربیان</a>
          <a class="header_nav profile" href="{% url 'accounts:athlete-login' %}">پنل ورزشکاران</a>
          {% endif %}
        </span>
      </div>

    </div>
  </span>
  <div class="mobile-header">
    <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">ورزش‌یار</button>
      <div id="myDropdown" class="dropdown-content">
        <a href="{% url 'gym:home' %}">صفحه اصلی</a>
        <a href="{% url 'gym:gyms' %}">باشگاه ها</a>
        <a href="{% url 'gym:trainers' %}">مربی ها</a>
        <a href="{% url 'gym:exc-list' %}">حرکات ورزشی</a>
        {% if user.is_authenticated %}<!-- {{ user.username }} عزیز، خوش آمدید! -->
        <a href="{% url 'accounts:profile' %}">پروفایل</a>
        {% else %}
        <a href="{% url 'accounts:trainer-login' %}">پنل مربیان</a>
        <a href="{% url 'accounts:athlete-login' %}">پنل ورزشکاران</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

<body>
  <div class="gym-title curved">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#80DEEA" fill-opacity="1"
        d="M0,96L60,80C120,64,240,32,360,53.3C480,75,600,149,720,202.7C840,256,960,288,1080,250.7C1200,213
        ,1320,107,1380,53.3L1440,0L1440,0L1380,0C1320,0,1200,0,1080,0C960,0,840,0,720,0C600,0,480,0,360,0C240,0,120,0,60,0L0,0Z">
      </path>
    </svg>
    <div class="logo-design">
      <img src="../../static/gym/svg/work-out.png">
      <div>
        <h1>ورزشیار</h1>
        <h3>راهنمایی به سوی انتخاب هوشمندانه مربی و باشگاه ورزشی</h3>
      </div>
    </div>
  </div>
  <main class="content">
    <div class="article">
      <span>
        <p>
          به "ورزش‌یار" خوش آمدید، پلتفرمی که به ورزشکاران کمک می‌کند تا بهترین مسیر را
          برای پیشرفت و موفقیت ورزشی خود انتخاب کنند. با استفاده از "ورزشیار"، شما می‌توانید به راحتی از میان باشگاه‌ها
          و مربیان مختلف، انتخابی هوشمندانه داشته باشید و تمرینات خود را به سطح جدیدی ببرید.
        </p>
      </span>
      <span>
        <img src="../../static/gym/svg/gym.jpg">
      </span>
    </div>
    <div class="article">
      <span>
        <img src="../../static/gym/svg/coach.avif">
      </span>
      <span>
        <p>
          در "ورزش‌یار"، شما با مجموعه‌ای از بهترین باشگاه‌ها و مربیان در سراسر کشور آشنا خواهید شد. هر ورزشکار می‌تواند
          با
          استفاده از پروفایل‌های کامل و نظرات سایر کاربران،
          مربی و باشگاه مناسب خود را انتخاب کند. ما اینجا هستیم تا شما بهترین تصمیم‌ها را برای پیشرفت ورزشی‌تان بگیرید.
        </p>
      </span>
    </div>
    <div class="article">
      <span>
        <p>
          ثبت‌نام در "ورزش‌یار" ساده و سریع است. تنها با چند کلیک، می‌توانید پروفایل شخصی خود را ایجاد کنید،
          رشته ورزشی مورد علاقه‌تان را انتخاب کنید و به جستجوی مربیان و باشگاه‌های مختلف بپردازید.
          شما دیگر نیازی به جستجوی طولانی و زمان‌بر برای پیدا کردن مربی و باشگاه مناسب ندارید. . </p>
      </span>
      <span>
        <img src="../../static/gym/svg/computer.avif">
      </span>
    </div>
  </main>
</body>
<footer>
  <h4>ارتباط با ما</h4>
  <h4>پشتیبانی</h4>
  <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
</footer>

</html>